// Textos da tela de acesso em pt-BR, inglês e chinês simplificado. Sprint: S10 | Risco: None
// O painel e a operação continuam em português; o aviso deixa isso claro antes do login.

export const TEXTOS_ENTRADA = {
  pt: {
    titulo: "Entrar — Psyra AI",
    idioma: "Idioma",
    eyebrow: "Saúde psicossocial · Conformidade NR-1",
    perguntaAntes: "Como você quer ",
    perguntaDestaque: "entrar",
    perguntaDepois: "?",
    apoio: "Escolha o acesso certo para o seu papel.",
    perfis: {
      empresa: {
        rotulo: "Empresa cliente",
        titulo: "Entrar no painel",
        descricao: "Resultados agregados por grupo (n ≥ 5), conformidade NR-1 e plano de ação.",
      },
      superadmin: {
        rotulo: "Operação Psyra",
        titulo: "Entrar na operação",
        descricao: "Equipe interna: empresas, planos e contas de acesso.",
      },
    },
    semContaTitulo: "Sua empresa ainda não tem acesso?",
    semContaTexto: "As contas são criadas pela equipe Psyra depois do diagnóstico gratuito.",
    solicitar: "Solicitar acesso",
    assunto: "Solicitar acesso à Psyra",
    trocar: "Trocar tipo de acesso",
    email: "E-mail",
    senha: "Senha",
    mostrarSenha: "Mostrar senha",
    ocultarSenha: "Ocultar senha",
    erroVazio: "Informe e-mail e senha.",
    entrando: "Entrando…",
    entrar: "Entrar",
    privacidade: "Resultados sempre por grupo. Nunca dados individuais.",
    voltar: "Voltar à página inicial",
    avisoIdioma: null,
  },
  en: {
    titulo: "Sign in — Psyra AI",
    idioma: "Language",
    eyebrow: "Psychosocial health · NR-1 compliance",
    perguntaAntes: "How do you want to ",
    perguntaDestaque: "sign in",
    perguntaDepois: "?",
    apoio: "Choose the access that matches your role.",
    perfis: {
      empresa: {
        rotulo: "Client company",
        titulo: "Sign in to the dashboard",
        descricao: "Results aggregated by group (n ≥ 5), NR-1 compliance and action plan.",
      },
      superadmin: {
        rotulo: "Psyra operations",
        titulo: "Sign in to operations",
        descricao: "Internal team: companies, plans and access accounts.",
      },
    },
    semContaTitulo: "Your company doesn't have access yet?",
    semContaTexto: "Accounts are created by the Psyra team after the free assessment.",
    solicitar: "Request access",
    assunto: "Request access to Psyra",
    trocar: "Change access type",
    email: "E-mail",
    senha: "Password",
    mostrarSenha: "Show password",
    ocultarSenha: "Hide password",
    erroVazio: "Enter your e-mail and password.",
    entrando: "Signing in…",
    entrar: "Sign in",
    privacidade: "Results always by group. Never individual data.",
    voltar: "Back to the home page",
    avisoIdioma: "The dashboard and the questionnaire are in Brazilian Portuguese.",
  },
  zh: {
    titulo: "登录 — Psyra AI",
    idioma: "语言",
    eyebrow: "心理社会健康 · 符合 NR-1",
    perguntaAntes: "您想以哪种身份",
    perguntaDestaque: "登录",
    perguntaDepois: "？",
    apoio: "请选择与您角色相符的入口。",
    perfis: {
      empresa: {
        rotulo: "客户企业",
        titulo: "登录仪表板",
        descricao: "按群组汇总的结果（n ≥ 5）、NR-1 合规和行动计划。",
      },
      superadmin: {
        rotulo: "Psyra 运营",
        titulo: "登录运营后台",
        descricao: "内部团队：企业、套餐和访问账户。",
      },
    },
    semContaTitulo: "您的企业还没有账户？",
    semContaTexto: "账户由 Psyra 团队在免费诊断之后创建。",
    solicitar: "申请开通",
    assunto: "申请开通 Psyra",
    trocar: "更换登录类型",
    email: "电子邮箱",
    senha: "密码",
    mostrarSenha: "显示密码",
    ocultarSenha: "隐藏密码",
    erroVazio: "请输入电子邮箱和密码。",
    entrando: "正在登录…",
    entrar: "登录",
    privacidade: "结果始终按群组呈现，绝不显示个人数据。",
    voltar: "返回首页",
    avisoIdioma: "仪表板和问卷目前为巴西葡萄牙语。",
  },
};
